### ISSUE TITLE
Date/Time for Override

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/pmps-ui#2]
Either an embedded ms calculator, for translation from Months/Weeks/Days/Hours/Minutes or some other way to enter a time for the overrides time.

**Comment by hhslepicka** [comment]
Started work to support this display at https://github.com/slaclab/pydm/pull/664

**Comment by hhslepicka** [comment]
Waiting on the `RemaningTime` PV instead of the Elapsed time so we can use also the new PyDMDateTimeLabel to represent when the override will be terminated.

**Comment by slacAWallace** [comment]
I added it to the library, but it won't get pushed to HXR until tomorrow evening.

We should spin this up on the K line to continue testing.

**Comment by slacAWallace** [comment]
Just missed using this this morning.

`PMPS:KFE:FFO:01:FF:007:Ovrd:RemainingTime_RBV`

**Comment by hhslepicka** [comment]
We can push to add it in...

**Comment by cristinasewell** [comment]
@ZLLentz is this the PR Alex mentioned over the email about the ***date time field change from the PMPS library side*** - or is that separate? If this is the one, what are the backwards compatibility issues related to it - is that on the PLC side?

**Comment by ZLLentz** [comment]
Yes, the PLCs probably need some adjustments to facilitate this.

The current PLC API is "give me an integer in milliseconds, then I will override this fast fault for that duration", and this is reflected in the the pmps-ui.

I think the proposal is to change the PLC API to "give me a timestamp, then I will override until that time/date". It is conceivable that we could maintain a dual API to smooth over a transition where we have both a pv that expects ms and another pv that expects a timestamp and respect all update requests to either.

It may also be possible to do all the math in the UI itself and convert a datetime widget into a duration in ms (and convert it back for display), but this doesn't seem so stable. But maybe it's fine?

**Comment by hhslepicka** [comment]
@ZLLentz the current widget for DateTime can do both ways... write a relative value or absolute...
The issue with sending the duration is the fact that we have two fields on the screen and on the PLC...
Let me highlight the issue here that was discussed previously with @slacAWallace:
- User pick a date/time on the widget (which is set to relative)...
- The widget computes the relative value and put it to the duration PV...
- The user clicks on the button to enable
- The effective duration is now the value minus the time the user took between picking a date/time and clicking on the button.

That will unleash all kind of confusion on users and that was the reasoning behind changing the PLC code to expect a absolute timestamp in which case it would never have this kind of issue.

**Comment by ZLLentz** [comment]
I understand that this will look confusing to the user. I think they are already confused with the ms inputs so this is not a very convincing argument to me. But I still want to do it on the PLC out of principle.

**Comment by hhslepicka** [comment]
In this case, merge away! 🤷‍♂️

**Comment by cristinasewell** [comment]
I love those Date/Time widgets - supper cool!!

One thing that I am missing from that PR probably because I have not used the time widgets before is - do we need a PV in the `PyDMDateTimeEdit` to send the info to? would this usually be the same as the one from the `PyDMDateTimeLabel`? or some other `Duration` PV - the reason I ask is because I think we don't have any PVs in the TimeEdit widget now (unless i am missing something there too - if so disregard this) and I was wondering how that's linked?

**Comment by ZLLentz** [comment]
> I still want to do it on the PLC out of principle

**Comment by ZLLentz** [comment]
I'll look more closely at the PR, etc. after PAMM

**Comment by hhslepicka** [comment]
@cristinasewell they do take a PV for the channel and also some other properties like `textFormat`.
Here is an example:
https://github.com/pcdshub/pmps-ui/pull/24/files#diff-c1964e3964d6175f683271721dc1173e687d31e239c57acdff0858a32af8e3b1R437-R442

Here is the widget code:
https://github.com/slaclab/pydm/blob/master/pydm/widgets/datetime.py
