### ISSUE TITLE
Remove Pulse Energy Fields

### ISSUE THREAD

**Issue by slacAWallace** [pcdshub/pmps-ui#28]
Remove pulse energy field from all areas of the diagnostic.

**Comment by cristinasewell** [comment]
This Issue could wait for #36 to be merged - because in that PR I'm actually placing the beam parameters in a separate `.ui` file - so we'll have to remove it again.

Or I could just partially remove the `Pulse Energy Fields` in #36 - and open a different PR that removes the Energy Fields from the rest of the ui?

**Comment by ZLLentz** [comment]
I think it's fine to do it either way, whichever is most convenient. You're the only one pushing code to this repo right now so the risk of strange merge conflicts is pretty low.

**Comment by cristinasewell** [comment]
Thank you - i'll do the later one then

**Comment by ZLLentz** [comment]
Both of the PRs that address this have been merged
